language: node_js
node_js:
  - "10"
  - stable

install:
  - yarn --frozen-lockfile

script:
  - yarn test
  - yarn lint

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
