interface Variadic {
  void simple1(DOMString... strings);
  void simple2(DOMString first, URL... urls);

  void overloaded1(DOMString... strings);
  void overloaded1(unsigned long... numbers);

  void overloaded2(DOMString first, DOMString... strings);
  void overloaded2(unsigned long first, DOMString... strings);
};
